import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/navbar/navbar";

const poppins = Poppins({
  subsets: ['latin'],          
  weight: ['400', '700'],     
  variable: '--font-poppins',  
});

export const metadata: Metadata = {
  title: "Zohrif",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={poppins.variable}>
      <body className="antialiased">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
